#!/usr/bin/env bash

anybox_dir="$(dirname "$0")"
cd "$anybox_dir" || {
  echo "Failed to cd into anybox dir: $anybox_dir"
  exit 1
}

source load_skel

see() {
  for i in "${skel_files[@]}"; do
    echo diff -q "$HOME/$i" "./skel/$i"
    if ! diff -q "$HOME/$i" "./skel/$i"; then
      echo "$i"
    fi
  done
}

if [ "$1" == 'see' ]; then
  see
elif [ "$1" == 'diff' ]; then
  diff
elif [ "$1" == 'install' ]; then
  diff
else
  echo "Usage: $0 {see|diff|install}"
  exit 1
fi

exit 1

echo "*** Installing $dryrun ***"
echo
rsync -acv $dryrun skel/ ~/
echo

if [ $# = 0 ]; then
  echo "Available workspaces:"
  ls ws
  exit
fi

for ws in "$@"; do
  echo
  echo "*** Applying workspace $ws ***"
  echo
  if [ -d "ws/$ws" ]; then
    if [ "$dryrun" != "" ]; then
      mkdir -p "$HOME/.ws/$ws/"
    else
      echo "Creating $HOME/.ws/$ws/"
    fi
    rsync -acv $dryrun "ws/$ws/" "$HOME/.ws/$ws/"
    if [ -d "ws/$ws/.bashrc.d" ]; then
      rsync -acv $dryrun "ws/$ws/.bashrc.d/" "$HOME/.bashrc.d/"
    fi

    setup_file="$HOME/.ws/$ws/setup"
    if [ -f "$setup_file" ] && [ -x "$setup_file" ]; then
      ( # subprocess so cwd doesn't change
        cd "$HOME/.ws/$ws/"
        if [ "$dryrun" == "" ]; then
          echo "Running ./setup"
          ./setup
        else
          echo "(DRY_RUN) Would run ./setup"
        fi
      )
    elif [ -e "$setup_file" ]; then
      echo "Error: setup isn't an executable"
    fi
  else
    echo "Workspace not found: $ws"
  fi
done

