#!/usr/bin/env bash

vhome_dir="$(dirname "$(readlnik -f $0 2>/dev/null || echo $0)")"
cd "$vhome_dir" || {
    echo "Failed to cd into vhome dir: $vhome_dir"
    exit 1
}

if [ "$1" != 'force' ]; then
    echo "NOTE: Add 'force' as FIRST argument to actually install"
    dryrun='--dry-run'
else
    shift
fi

echo "*** Installing $dryrun ***"
echo
rsync -acv $dryrun skel/ ~/
echo

if [ $# = 0 ]; then
    echo "Available workspaces:"
    ls ws
    exit
fi

for ws in "$@"; do
    echo
    echo "*** Applying workspace $ws ***"
    echo
    if [ -d "ws/$ws" ]; then
        if [ "$dryrun" != "" ]; then
            mkdir -p "$HOME/.ws/$ws/"
        else
            echo "Creating $HOME/.ws/$ws/"
        fi
        rsync -acv $dryrun "ws/$ws/" "$HOME/.ws/$ws/"
        if [ -d "ws/$ws/.bashrc.d" ]; then
            rsync -acv $dryrun "ws/$ws/.bashrc.d/" "$HOME/.bashrc.d/"
        fi

        setup_file="$HOME/.ws/$ws/setup"
        if [ -f "$setup_file" ] && [ -x "$setup_file" ]; then
            ( # subprocess so cwd doesn't change
                cd "$HOME/.ws/$ws/"
                if [ "$dryrun" == "" ]; then
                    echo "Running ./setup"
                    ./setup
                else
                    echo "(DRY_RUN) Would run ./setup"
                fi
            )
        elif [ -e "$setup_file" ]; then
            echo "Error: setup isn't an executable"
        fi
    else
        echo "Workspace not found: $ws"
    fi
done

