#!/usr/bin/env bash

# fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Set homebrew ruby stuff
ruby_dir="/usr/local/opt/ruby/bin"
if [ -d "$ruby_dir" ]; then
    PATH="$PATH:"$ruby_dir""
fi

# set homebrew sbin stuff
brew_sbin="/usr/local/sbin"
if [ -d "$brew_sbin" ]; then
    PATH="$PATH:$brew_sbin"
fi

# Set mac python bin
pyth_bin="$HOME/Library/Python/3.7/bin"
if [ -d "$pyth_bin" ]; then
    PATH="$PATH:$pyth_bin"
fi

which ipython &>/dev/null && alias ipy='ipython --TerminalInteractiveShell.editing_mode=vi'

if which code &>/dev/null; then
    alias ch='code .'
fi
