# The minimal config to make mouse scrolling work
set -g mouse on

# Use vim-style keys to move between panes after the tmux prefix (C-b).
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
